;;; -*- mode: Lisp; coding: utf-8-unix -*-

(in-package :repl)

(require "isa")

(define-isa bacaw-isa
    (:NOP (0 0))
    (:INT (#x0 #x7))
    (:HALT (0 8))
    (:CLS (0 #xe))
    (:INC (#x1) :ulong)
    (:ADDI (#x2 #x1))
    (:SUBI (#x2 #x9))
    (:MULI (#x2 #x2))
    (:DIVI (#x2 #xa))
    (:CMPI (#x2 0))
    (:ADDF (#x4 #x1))
    (:SUBF (#x4 #x9))
    (:MULF (#x4 #x2))
    (:DIVF (#x4 #xa))
    (:CMPF (#x4 0))
    (:CEIL (#x4 #x6))
    (:LOAD (#x5) :long)
    (:POP (#x6))
    (:CALL (#x7 #x7) :ulong)
    (:RET (#x7 #xc))
    (:CIE (#x7 #x0))
    (:SIE (#x7 #x8))
    (:RESET (#x7 #x1))
    (:MOV (#x8))
    (:DEC (#x9) :ulong)
    (:STORE (#xD) :long)
    (:PUSH (#xE)))
