;;; -*- mode: Lisp; coding: utf-8-unix -*-

(defvar *COMPILER* 0)

(require "runtime/truth")
(require "runtime/eq")
(require "runtime/null")
(require "runtime/number")
(require "runtime/float")
(require "runtime/cmp")
(require "runtime/math")
(require "runtime/bitops")
(require "runtime/logic")
(require "runtime/error")
(require "runtime/memory")
(require "runtime/array")
(require "runtime/string")
(require "runtime/concatenate")
(require "runtime/package")
(require "runtime/io")
