(defun test-cps-transform ()
  (assert-matches '((abc (RETURN abc))
                    ((boo 1 2 3) (boo 1 2 3 RETURN))
                    ((boo (who))
                     (who (λ (:R) (boo :R RETURN))))
                    ((+ 2 (* 3 4) 5)
                     (* 3 4 (λ (:R) (+ 2 :R 5 RETURN))))
                    ((+ 2 (sqrt (* 3 4)) 5)
                     (* 3 4 (λ (:R0) (sqrt :R0 (λ (:R1) (+ 2 :R1 5 RETURN))))))
                    ((lambda (x) x) (lambda (x) (RETURN x)))
                    ((lambda (x) (* x x)) (lambda (x) (* x x RETURN)))
                    ((if (> a b) (boo a) (boo b))
                     (> a b (λ (TEST)
                               (if TEST
                                   (boo a RETURN)
                                   (boo b RETURN)))))
                    ((if a (boo a) (boo b))
                     (if a
                         (boo a RETURN)
                         (boo b RETURN)))
                    ((if (> a b) a b)
                     (> a b (λ (TEST)
                               (if TEST
                                   (RETURN a)
                                   (RETURN b)))))
                    ((if x (boo)) (if x (boo return) (RETURN nil)))
                    ((who (if (> a b) (boo a) b))
                     (> a b (λ (TEST)
                               (if TEST
                                   (boo a (λ (:R) (who :R RETURN)))
                                   (who b RETURN)))))
                    ((lambda (x y) (if (> x y) x y))
                     (lambda (x y)
                       (> x y (λ (TEST) (if TEST (RETURN x) (RETURN y))))))
                    ((boo (lambda (x) (who x)) 3)
                     (boo (lambda (x) (who x RETURN)) 3 RETURN))
                    ((boo (if night you me))
                     (if night (boo you RETURN) (boo me RETURN)))
                    ((defun fn (x) (* x x))
                     (defun fn (x) (* x x RETURN))))
                  :fn #'nolisp:cps-transform))
