;;; -*- mode: Lisp; coding: utf-8-unix -*-

(console-write-unsigned-integer *string-segment*)
(console-write "Hello:\n")
(console-write-unsigned-integer "Hello:\n")
(console-write "EQ:")
(console-write-unsigned-integer (eq :hello :hello))
(console-write-unsigned-integer (eq 'hello 'hello))
(console-write-unsigned-integer 'hello)
(console-write "Symbol:")
(console-write-unsigned-integer (keyword? 'hello))
(console-write 'hello)
(console-write (symbol-name 'hello))
(console-write "Keyword:")
(console-write-unsigned-integer (keyword? :hello))
(console-write-unsigned-integer :hello)
(console-write :hello)
(console-write (symbol-name :hello))
(console-write "Quoted Keyword:")
(console-write-unsigned-integer (keyword? ':hello))
(console-write-unsigned-integer ':hello)
(console-write ':hello)
(console-write (symbol-name ':hello))
(console-write "Hashed Quoted Keyword:")
(console-write-unsigned-integer (keyword? #:hello))
(console-write-unsigned-integer #:hello)
(console-write #:hello)
(console-write (symbol-name #:hello))
