(defun test-match ()
  (assert-equal (nolisp:match '?x 1) '((?x . 1)))
  (assert-equal (nolisp:match :x 1) '((:x . 1)))
  (assert-equal (nolisp:match '?x '(abc 1)) '((?x . (abc 1))))
  (assert-equal (nolisp:match '(?x) '(1)) '((?x . 1)))
  (assert-equal (nolisp:match '(?x) '(1 2)) nil)
  (assert-equal (nolisp:match '(?x 2) '(1 2)) '((?x . 1)))
  (assert-equal (nolisp:match '(1 ?x) '(1 2)) '((?x . 2)))
  (assert-equal (nolisp:match '(2 ?x) '(1 2)) nil)
  (assert-equal (nolisp:match '(?x ?x) '(2 2)) '((?x . 2)))
  (assert-equal (nolisp:match '(?x ?x) '(1 2)) nil)
  (assert-equal (nolisp:match '(a ?x 1) '(a xyz 1)) '((?x . xyz)))
  (assert-equal (nolisp:match '(a ?x 1) '(b xyz 1)) nil)
  (assert-equal (nolisp:match '(a (foo ?x) 1) '(a (foo (a b)) 1)) '((?x . (a b))))
  (assert-equal (nolisp:match '(a :x 1) '(a xyz 1)) '((:x . xyz))))
