;;; -*- mode: Lisp; coding: utf-8-unix -*-

(require "assert")
(require "runtime/math.nl")
(require "runtime/halt.nl")

(defun test-add ()
  (assert-equal (+ 2 2) 4)
  (assert-equal (+ -2 2) 0))

(defun test-sub ()
  (assert-equal (- 3) -3)
  (assert-equal (- -3) 3)
  (assert-equal (- 2 2) 0)
  (assert-equal (- -2 2) -4)
  (assert-equal (- 4 2) 2))

(defun test-mul ()
  (assert-equal (* 2 2) 4)
  (assert-equal (* -2 2) -4)
  (assert-equal (* 2 1) 2)
  (assert-equal (* 0 2) 0))

(defun test-div ()
  (assert-equal (/ 2 2) 1)
  (assert-equal (/ -2 2) -1)
  (assert-equal (/ 4 2) 2)
  (assert-equal (/ 2 4) 0))

(defun test-mod ()
  (assert-equal (mod 2 2) 0)
  (assert-equal (mod -2 2) 0)
  (assert-equal (mod 2 -2) 0)
  (assert-equal (mod 4 2) 0)
  (assert-equal (mod 2 4) 2)
  (assert-equal (mod 3 2) 1)
  (assert-equal (mod -1 2) -1)
  (assert-equal (mod 1 -2) 1))

(defun test-expt ()
  (assert-equal (expt 2 3) 8)
  (assert-equal (expt 8 -1) 0)
  (assert-equal (expt 100 1) 100)
  (assert-equal (expt 100 0) 1))

(defun test-log2 ()
  (assert-equal (log2 123) 6)
  (assert-equal (log2 4567) 12))

(defun test-log ()
  (assert-equal (log 123 10) 2)
  (assert-equal (log 12345 10) 4)
  (assert-equal (log 1234 16) 2)
  (assert-equal (log 12345 16) 3))

(defun test-math ()
  (test-add)
  (test-sub)
  (test-mul)
  (test-div)
  (test-mod)
  (test-expt)
  (test-log2)
  (test-log))

(run-test-suite test-math)
