;;; -*- mode: Lisp; coding: utf-8-unix -*-

(require "runtime/bc/io/console")
(require "runtime/bc/io/node_console")
(require "runtime/halt")
(require "runtime/itoa")

(var *banner* "WELCOME!!")

(node-output-write 'hello-world)
(console-write "\n\n")
(console-write *banner*)
(console-write-integer -123)
(with-allocation (str 48)
  (console-write "\nLog2:\t")
  (console-write-integer (log2-unsigned 1234))
  (console-write "\nLog3:\t")
  (console-write (itoa (log 1234 3) str 10))
  (console-write "\nMax digit:\t")
  (console-write-integer (count-digits-brute 1234 3))
  (console-write "\nMax digit guess:\t")
  (console-write-integer (count-digits-guesser 1234 3))
  (console-write "\n\nDec:\t")
  (console-write (itoa 1234 str))
  (console-write "\nHex:\t")
  (console-write (itoa #x-1234 str 16))
  (console-write "\nOct:\t")
  (console-write (itoa #x-1234 str 8))
  (console-write "\nBin:\t")
  (console-write (itoa #x-1234 str 2))
  (console-write "\nTern:\t")
  (console-write (itoa #x-1234 str 3))
  (console-write "\nThirteen:\t")
  (console-write (itoa #x-1234 str 13))
  (console-write "\n26:\t")
  (console-write (itoa #x-1234 str 26))
  (console-write "\n52:\t")
  (console-write (itoa #x-1234 str 52))
  (console-write "\n64:\t")
  (console-write (itoa #x-1234 str 64))
  (console-write "\nBin FFFF:\t")
  (console-write (itoa-unsigned #xFFFF str 2))
  (console-write "\nBin -FFFF:\t")
  (console-write-integer (count-digits-brute #x-FFFF 2))
  (console-write "\n\t")
  (console-write (itoa-unsigned #x-FFFF str 2))
  (console-write "\n\t")
  (console-write (itoa-unsigned #x-1 str 2))
  (console-write "\n"))
(console-write "\nGood bye...\n")

(halt)
