;;; -*- mode: Lisp; coding: utf-8-unix -*-

(require "runtime/bc/io/console")
(require "runtime/bc/io/node_console")
(require "runtime/halt")

(defun print-buffer-stats ()
  (node-output-write "\nRead: ")
  (node-output-write-integer (node-input-bytes-read))
  (node-output-write "\nEOS: ")
  (node-output-write-integer (node-input-eos))
  (node-output-write "\nNext byte: ")
  (node-output-write-integer node-input-next-byte))

(defun dump-input-buffer (&optional (max 32) (n 0))
  (if (< n max)
      (progn
        (node-output-write "\n")
        (node-output-write-integer n)
        (node-output-write ": ")
        (node-output-write-integer (ptr-read-ubyte (+ node-input-base-addr n)))
        (dump-input-buffer max (+ n 1)))))

(node-output-write-integer (count-digits #xF0000000 16))
(node-output-write "\n")
(node-output-write-integer 1234 2)
                                        ;(node-output-write-integer 1234 3)
(node-output-write-integer -1234 16)
(node-output-write-integer -1234 10)
(node-output-write-integer #x-BCD 16)
(node-output-write-integer #x-BCE)

(node-output-write-integer #xFFFFFFFF 16)
(node-output-write-unsigned-integer #xFFFFFFFF 16)
(node-output-write-unsigned-integer node-input-base-addr 16)
(print-buffer-stats)
(dump-input-buffer)

(node-output-write "\nName? ")
(with-allocation (buffer 128)
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (print-buffer-stats)
  (dump-input-buffer)
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  (node-output-write-integer (node-input-read-next))
  (node-output-write "\n")
  ;;(node-output-write (node-input-read buffer 128))
  (node-output-write "\n")
  (node-input-wait)
  (print-buffer-stats)
  )
